name: sign_in_with_apple
description: A placeholder plugin to override sign_in_with_apple on Android
version: 0.0.1
homepage: https://example.com
environment:
  sdk: ">=3.0.0 <4.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: fake.signin
        pluginClass: FakeSignInPlugin

